### ISSUE TITLE
Diagnostic web page broken in 0.50.0-ea7.

### ISSUE THREAD

**Issue by dgaffuri** [datawire/ambassador#1019]
**Describe the bug**
Diagnostic web page is broken in 0.50.0-ea7

**To Reproduce**
1. kubectl port-forward &lt;ambassador-pod&gt; 8877
2. Navigate to http://localhost:8877/ambassador/v0/diag/
3. Browser displays 'server error'

**Expected behavior**
Browser should show the diagnostic page

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-ea7
 - Kubernetes environment: Docker Desktop Community 2.0.0.0-mac81 (29211)
 - Version: 1.10.3

**Additional context**
The following is shown in logs:
```
2018-12-07 16:31:23 diagd 0.50.0 [P50TThreadPoolExecutor-0_3] INFO: E32627D4-8486-4091-A419-A103CCF431B4: 127.0.0.1 "GET /ambassador/v0/diag/" START
2018-12-07 16:31:23 diagd 0.50.0 [P50TThreadPoolExecutor-0_3] ERROR: 'kind'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 98, in wrapper
    result = f(*args, reqid=reqid, **kwds)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 299, in show_overview
    aconf = get_aconf(app, "overview")
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 173, in get_aconf
    resources = fetch_resources(latest, app.logger, k8s=app.k8s)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/acresource.py", line 258, in fetch_resources
    fetcher = ResourceFetcher(config_dir_path, logger, k8s=k8s)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/acresource.py", line 155, in __init__
    self.load_yaml(serialization, k8s=k8s)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/acresource.py", line 171, in load_yaml
    self.ocount = self.process_object(obj, rkey)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/acresource.py", line 220, in process_object
    if obj['kind'] == 'Pragma':
KeyError: 'kind'
2018-12-07 16:31:23 diagd 0.50.0 [P50TThreadPoolExecutor-0_3] ERROR: E32627D4-8486-4091-A419-A103CCF431B4: 127.0.0.1 "GET /ambassador/v0/diag/" 30ms 500 server error
```

**Comment by nbkrause** [comment]
This is known and will be fixed in GA.

**Comment by kflynn** [comment]
Fixed in -rc1.
