### ISSUE TITLE
pod cannot start - SSL certificate verify failed

### ISSUE THREAD

**Issue by brianmori** [datawire/ambassador#1030]
**Describe the bug**
I installed Ambassador on a new Kubernetes cluster from Alibaba

**To Reproduce**
Install ambassador with the Kubernetes guide

https://www.getambassador.io/user-guide/getting-started/

kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml
kubectl apply -f ambassador-service.yaml

**Expected behavior**
Ambassador pods to be running

**Versions (please complete the following information):**
 - Ambassador: 0.40.2
 - Kubernetes environment : Alibaba
 - Version 1.11.5

**Additional context**

Is there a way to disable the certificate verification ?

ambassador-f646678c-42hr2   0/1     CrashLoopBackOff   25         1h
ambassador-f646678c-8h2mv   0/1     CrashLoopBackOff   25         1h
ambassador-f646678c-m975p   0/1     CrashLoopBackOff   25         1h

2018-12-11 06:28:14,007 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
2018-12-11 06:28:14 kubewatch 0.40.0 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
2018-12-11 06:28:14,017 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
2018-12-11 06:28:14 kubewatch 0.40.0 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
2018-12-11 06:28:14,026 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
2018-12-11 06:28:14 kubewatch 0.40.0 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/default/configmaps
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()

**Comment by richarddli** [comment]
See https://www.getambassador.io/reference/running/#ambassador_verify_ssl_false.
