### ISSUE TITLE
Permission denied when running as non-root

### ISSUE THREAD

**Issue by inamilu** [datawire/ambassador#1368]
**Describe the bug**
I'm getting the following error when running the Ambassador image as a non-root user:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 554, in run
    self.load_config_fs(arg)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 581, in load_config_fs
    self._load_ir(aconf, fetcher, scc.null_reader, snapshot)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 627, in _load_ir
    if not self.validate_envoy_config(config=ads_config):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 665, in validate_envoy_config
    with open(app.ads_temp_path, "w") as output:
PermissionError: [Errno 13] Permission denied: '/tmp/envoy-test.json'
AMBASSADOR: pinging diagd (8)...
AMBASSADOR: diagd running
AMBASSADOR: waiting
PIDS: 92:ambex 93:diagd
```
**To Reproduce**
Since I can't pull the Ambassador image from its official Quay Repository due to security policies on the Kubernetes cluster I want to deploy, I've created first a container locally:

`docker run -it -p 8080:80 --name=ambassador quay.io/datawire/ambassador:0.51.2 --demo`

After that I've deployed the container into the Docker registry from where my Kubernetes cluster has the permissions to pull images.

Then, I started the pods with the following Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        "consul.hashicorp.com/connect-inject": "false"
      labels:
        service: ambassador
    spec:
      serviceAccountName: ambassador
      imagePullSecrets:
      - name: <my_secret>
      containers:
      - name: ambassador
        image: <my_registry>/ambassador:latest
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_CONFIG_BASE_DIR
          value: /tmp/ambassador-config
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8877
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      restartPolicy: Always
      securityContext:
        runAsUser: 8888
```
 
However, the above described error is produced. Is it a bug or am I not configuring the pods in the right way?

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.51.2]
 - Kubernetes environment [bare metal]

**Comment by richarddli** [comment]
Does the error go away if you run as root?

**Comment by kflynn** [comment]
0.51.2 is pretty old now; can you please check 0.70.1? I think it might do what you need.
