### ISSUE TITLE
ambassador throw "Service token file does not exists"

### ISSUE THREAD

**Issue by jinyuchen724** [datawire/ambassador#1437]
hi,
   i use ambassador-no-rbac.yaml to start ambassador:

ambassador-no-rbac.yaml:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
spec:
  type: NodePort
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: 8877
  selector:
    service: ambassador
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        "consul.hashicorp.com/connect-inject": "false"
      labels:
        service: ambassador
    spec:
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.50.2
        resources:
          limits:
            cpu: 4
            memory: 7Gi
          requests:
            cpu: 3
            memory: 5Gi
        env:
        - name: AMBASSADOR_VERIFY_SSL_FALSE
          value: "true"
        - name: AMBASSADOR_NO_KUBEWATCH
          value: "true"
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8877
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      nodeSelector:
        LB: ambassador
      hostNetwork: true
      restartPolicy: Always
```

$ kubectl  get all
```
NAME                                        READY   STATUS             RESTARTS   AGE
pod/ambassador-cc99cc497-64bcd              0/1     CrashLoopBackOff   7          15m
pod/ambassador-cc99cc497-h5j6v              0/1     CrashLoopBackOff   7          15m
pod/ambassador-cc99cc497-hcmbr              0/1     Error              7          12m
pod/kubernetes-dashboard-7b45bf8696-cmtpv   1/1     Running            0          4h46m
pod/nginx-deployment-77657b454b-bffrn       1/1     Running            0          31h
pod/nginx-deployment-77657b454b-wpblh       1/1     Running            0          31h

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)       AGE
service/kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP       5d9h
service/kubernetes-dashboard   ClusterIP   10.102.208.251   <none>        80/TCP        4h46m
service/my-nginx               NodePort    10.107.216.68    <none>        80:8080/TCP   30h

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ambassador             0/3     3            0           15m
deployment.apps/kubernetes-dashboard   1/1     1            1           4h46m
deployment.apps/nginx-deployment       2/2     2            2           31h

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/ambassador-cc99cc497              3         3         0       15m
replicaset.apps/kubernetes-dashboard-7b45bf8696   1         1         1       4h46m
replicaset.apps/nginx-deployment-77657b454b       2         2         2       31h
```

$ kubectl  logs pod/ambassador-cc99cc497-64bcd

```
2019-04-17 12:19:59 kubewatch [24 TMainThread] 0.50.2 INFO: kubewatch starting: mode 'cluster-id' ambassador_config_dir '/no/such/path' envoy_config_file '/dev/null' debug 'False' delay '1.0' pid 'None'
2019-04-17 12:19:59 kubewatch [24 TMainThread] 0.50.2 INFO: namespace default, watching all namespaces
2019-04-17 12:19:59 kubewatch [24 TMainThread] 0.50.2 WARNING: kubewatch failed!
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 527, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 518, in main
    watcher.run(id_only=True)
  File "/ambassador/kubewatch.py", line 334, in run
    v1 = kube_v1()
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/utils.py", line 432, in kube_v1
  File "/usr/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 93, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/usr/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/usr/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.
AMBASSADOR: kubewatch cluster-id exited with status 1
AMBASSADOR: shutting down (1)
```

why i use no-rbac.yaml,but still thorw “Service token file does not exists” error？
thank you for your answer～～～

**Comment by jinyuchen724** [comment]
who can help me?thank you great god～～～～！

**Comment by micemuni** [comment]
I am also facing the same error for kube podOperator, is this fixed..? or any solution??

```
[2020-03-04 14:50:22,276] {taskinstance.py:887} INFO - Executing <Task(KubernetesPodOperator): passing-task> on 2020-03-04T14:49:21.640386+00:00
[2020-03-04 14:50:22,280] {standard_task_runner.py:53} INFO - Started process 11 to run task
[2020-03-04 14:50:22,337] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: kubernetes_sample.passing-task 2020-03-04T14:49:21.640386+00:00 [running]> kubernetessamplepassingtask-15170bcf93ae48c9bc273b146fc9bbd3
[2020-03-04 14:50:22,357] {taskinstance.py:1128} ERROR - Service token file does not exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 200, in execute
    config_file=self.config_file)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/kubernetes/kube_client.py", line 103, in get_kube_client
    client_conf = _get_kube_config(in_cluster, cluster_context, config_file)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/kubernetes/kube_client.py", line 41, in _get_kube_config
    config.load_incluster_config()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 94, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.
[2020-03-04 14:50:22,358] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
```

**Comment by btrx-rkazi** [comment]
Even I am facing same issue

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    config.load_incluster_config()
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 73, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.
