### ISSUE TITLE
Handle timeout when validating envoy config

### ISSUE THREAD

**Issue by thrucker** [datawire/ambassador#1478]
**Describe the bug**
When the envoy config is updated, it is validated by running `envoy --config-path <path> --mode validate`. This currently has a fixed timeout of [5 seconds](https://github.com/datawire/ambassador/blob/9484c0b07465e1547cc57a8942d3374d4ef4cf66/ambassador/ambassador_diag/diagd.py#L874). However, when an actual timeout happens this is not properly handled and seems to crash the automatic reconfiguration of ambassador. 

This ultimately leads to a state where ambassador still runs and handles requests properly, but is not able to receive new route mappings anymore. In this case only a restart of ambassador seems to help.

**To Reproduce**
I'm not sure how one would reproduce such a timeout. At least in our case it seems to happen from time to time and results in the described behavior.

Looking into the code at https://github.com/datawire/ambassador/blob/9484c0b07465e1547cc57a8942d3374d4ef4cf66/ambassador/ambassador_diag/diagd.py#L873-L878 it seems that only `subprocess.CalledProcessError` is handled. According to the [python documentation](https://docs.python.org/3/library/subprocess.html#exceptions) a timeout will result in a `subprocess.TimeoutExpired` error.

Log Output:
```
2019-04-30 15:01:07 diagd 0.60.1 [P54TAmbassadorEventWatcher] ERROR: could not reconfigure: Command '['envoy', '--config-path', '/ambassador/snapshots/econf-tmp.json', '--mode', 'validate']' timed out after 5 seconds
2019-04-30 15:01:07 diagd 0.60.1 [P54TAmbassadorEventWatcher] ERROR: Command '['envoy', '--config-path', '/ambassador/snapshots/econf-tmp.json', '--mode', 'validate']' timed out after 5 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1535, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 891, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['envoy', '--config-path', '/ambassador/snapshots/econf-tmp.json', '--mode', 'validate']' timed out after 5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 590, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 708, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 727, in _load_ir
    if not self.validate_envoy_config(config=ads_config):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 874, in validate_envoy_config
    odict['output'] = subprocess.check_output(command, stderr=subprocess.STDOUT, timeout=5)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 430, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['envoy', '--config-path', '/ambassador/snapshots/econf-tmp.json', '--mode', 'validate']' timed out after 5 seconds
```

**Expected behavior**
In case a timeout happens it should be properly handled and not crash some parts of ambassador. Ideally we would also get the output of the subprocess on a `TimeoutExpired` error to further debug potential causes of the timeout.

**Versions:**
 - Ambassador: 0.60.1
 - Kubernetes environment: Google Kubernetes Engine
 - Kubernetes Version: v1.11.7-gke.12

**Comment by kflynn** [comment]
Out of curiosity, have you tried 0.60.2 yet? We've never seen that validation hit the timeout unless the CPU is pegged for other reasons, and 0.60.2 should make that less likely.

That being said, this is a real bug, though I'm not sure of the fix timeline yet. We'd happily take a PR, of course. :wink:

**Comment by thrucker** [comment]
We now switched to 0.60.3 and the timeouts seem to be gone (at least they're running since 24 hours without any timeout error). But as you said the bug should be fixed nevertheless.

**Comment by hakamadare** [comment]
#1652 contains an attempt to mitigate this issue.

**Comment by hpurmann** [comment]
Did #1652 fix it? Otherwise don't close please

**Comment by jwm** [comment]
Yup, the corresponding PR fixed this issue for us.

**Comment by kflynn** [comment]
Thanks for the confirmation!

**Comment by jfrabaute** [comment]
We're facing a similar problem.
The timeout exception is triggered (first problem) and an exception is raised from the code displaying the timeout message:

```
[ambassador-t9zrq] Traceback (most recent call last): 
[ambassador-t9zrq]   File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1385, in validate_envoy_config 
[ambassador-t9zrq]     odict['output'] = subprocess.check_output(command, stderr=subprocess.STDOUT, timeout=timeout) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/subprocess.py", line 411, in check_output 
[ambassador-t9zrq]     **kwargs).stdout 
[ambassador-t9zrq]   File "/usr/lib/python3.7/subprocess.py", line 490, in run 
[ambassador-t9zrq]     stdout, stderr = process.communicate(input, timeout=timeout) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/subprocess.py", line 964, in communicate 
[ambassador-t9zrq]     stdout, stderr = self._communicate(input, endtime, timeout) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/subprocess.py", line 1716, in _communicate 
[ambassador-t9zrq]     self._check_timeout(endtime, orig_timeout, stdout, stderr) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/subprocess.py", line 1011, in _check_timeout 
[ambassador-t9zrq]     stderr=b''.join(stderr_seq) if stderr_seq else None) 
[ambassador-t9zrq] subprocess.TimeoutExpired: Command '['envoy', '--config-path', '/ambassador/snapshots/econf-tmp.json', '--mode', 'validate']' timed out after 5 seconds 
[ambassador-t9zrq]  
[ambassador-t9zrq] During handling of the above exception, another exception occurred: 
[ambassador-t9zrq]  
[ambassador-t9zrq] Traceback (most recent call last): 
[ambassador-t9zrq]   File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit 
[ambassador-t9zrq]     msg = self.format(record) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/logging/__init__.py", line 869, in format 
[ambassador-t9zrq]     return fmt.format(record) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/logging/__init__.py", line 608, in format 
[ambassador-t9zrq]     record.message = record.getMessage() 
[ambassador-t9zrq]   File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage 
[ambassador-t9zrq]     msg = msg % self.args 
[ambassador-t9zrq] TypeError: not all arguments converted during string formatting 
[ambassador-t9zrq] Call stack: 
[ambassador-t9zrq]   File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap 
[ambassador-t9zrq]     self._bootstrap_inner() 
[ambassador-t9zrq]   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner 
[ambassador-t9zrq]     self.run() 
[ambassador-t9zrq]   File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 869, in run 
[ambassador-t9zrq]     self.load_config_watt(rqueue, url) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1047, in load_config_watt 
[ambassador-t9zrq]     self._load_ir(rqueue, aconf, fetcher, scc, snapshot) 
[ambassador-t9zrq]   File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1066, in _load_ir 
[ambassador-t9zrq]     if not self.validate_envoy_config(config=ads_config, retries=self.app.validation_retries): 
[ambassador-t9zrq]   File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1396, in validate_envoy_config 
[ambassador-t9zrq]     timeout, ', retrying...' if retry < retries - 1 else '', e.output) 
[ambassador-t9zrq] Message: 'envoy configuration validation timed out after {} seconds{}\n{}'
```

So there seem to be an error in the `self.logger.warn` line added with the fix https://github.com/datawire/ambassador/pull/1652 .
The timeout is a different problem, probably not a but, but maybe something we could configure.
I suppose I should open a new issue, or we can reopen the same issue.

**Comment by jfrabaute** [comment]
I sent a PR for the logging problem: https://github.com/datawire/ambassador/pull/2766
