### ISSUE TITLE
panic: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource

### ISSUE THREAD

**Issue by aminebizid** [datawire/ambassador#1548]
**Describe the bug**
```bash
k get pod
NAME                         READY     STATUS             RESTARTS   AGE
ambassador-6d4b649fd-bflwk   0/1       CrashLoopBackOff   5          3m
```

```
k logs -f ambassador-6d4b649fd-bflwk
AMBASSADOR STARTING with environment:
====
AMBASSADOR_ADMIN_PORT=tcp://10.43.165.34:8877
AMBASSADOR_ADMIN_PORT_8877_TCP=tcp://10.43.165.34:8877
AMBASSADOR_ADMIN_PORT_8877_TCP_ADDR=10.43.165.34
AMBASSADOR_ADMIN_PORT_8877_TCP_PORT=8877
AMBASSADOR_ADMIN_PORT_8877_TCP_PROTO=tcp
AMBASSADOR_ADMIN_SERVICE_HOST=10.43.165.34
AMBASSADOR_ADMIN_SERVICE_PORT=8877
AMBASSADOR_ADMIN_SERVICE_PORT_AMBASSADOR_ADMIN=8877
AMBASSADOR_NAMESPACE=default
AMBASSADOR_PORT=tcp://10.43.48.0:80
AMBASSADOR_PORT_80_TCP=tcp://10.43.48.0:80
AMBASSADOR_PORT_80_TCP_ADDR=10.43.48.0
AMBASSADOR_PORT_80_TCP_PORT=80
AMBASSADOR_PORT_80_TCP_PROTO=tcp
AMBASSADOR_ROOT=/ambassador
AMBASSADOR_SERVICE_HOST=10.43.48.0
AMBASSADOR_SERVICE_PORT=80
====
2019-05-16 08:06:20 kubewatch [26 TMainThread] 0.61.0 DEBUG: looking up ID for namespace default
2019-05-16 08:06:21 kubewatch [26 TMainThread] 0.61.0 DEBUG: cluster ID URL is d6e_id://7ec1b534-5d0e-11e9-89f7-000d3a441aef/default
2019-05-16 08:06:21 kubewatch [26 TMainThread] 0.61.0 DEBUG: cluster ID is 28ffb55a-dc0b-5045-ad16-173a438014c3 (from namespace default)
AMBASSADOR: using cluster ID 28ffb55a-dc0b-5045-ad16-173a438014c3
AMBASSADOR: starting ads
AMBASSADOR: starting diagd
AMBASSADOR: pinging diagd (10)...
time="2019-05-16T08:06:21Z" level=info msg="Ambex 0.1.1 starting..."
time="2019-05-16T08:06:21Z" level=info msg=Listening port=18000
time="2019-05-16T08:06:21Z" level=info msg="Wrote PID" file=ambex.pid pid=33
time="2019-05-16T08:06:21Z" level=info msg="Pushing snapshot v0"
AMBASSADOR: pinging diagd (9)...
2019-05-16 08:06:23 diagd 0.61.0 [P34TMainThread] INFO: thread count 5, listening on 0.0.0.0:8877
[2019-05-16 08:06:23 +0000] [34] [INFO] Starting gunicorn 19.9.0
[2019-05-16 08:06:23 +0000] [34] [INFO] Listening at: http://0.0.0.0:8877 (34)
[2019-05-16 08:06:23 +0000] [34] [INFO] Using worker: threads
[2019-05-16 08:06:23 +0000] [48] [INFO] Booting worker with pid: 48
2019-05-16 08:06:23 diagd 0.61.0 [P48TAmbassadorEventWatcher] INFO: starting event watcher
AMBASSADOR: pinging diagd (8)...
AMBASSADOR: diagd running
+ set +x
+ /ambassador/watt --notify 'sh /ambassador/post_watt.sh' -s service --watch /ambassador/watch_hook.py
AMBASSADOR: waiting
PIDS: 33:ambex 34:diagd 54:watt
panic: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource

goroutine 1 [running]:
github.com/datawire/teleproxy/pkg/k8s.NewClient(0x0, 0xc000138410)
	/home/circleci/repo/pkg/k8s/client.go:148 +0x1c0
main._runWatt(0x1ef3200, 0xc00008e960, 0x0, 0x6, 0x0)
	/home/circleci/repo/cmd/watt/main.go:56 +0x4d
main.runWatt(0x1ef3200, 0xc00008e960, 0x0, 0x6)
	/home/circleci/repo/cmd/watt/main.go:46 +0x49
github.com/spf13/cobra.(*Command).execute(0x1ef3200, 0xc00003a080, 0x6, 0x6, 0x1ef3200, 0xc00003a080)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1ef3200, 0xc00039bf88, 0x407460, 0xc000090058)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1ef3200, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	/home/circleci/repo/cmd/watt/main.go:146 +0x2d
AMBASSADOR: watt exited with status 2
```

**To Reproduce**
```bash
kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml

kubectl apply -f ambassador-service.yaml
```

ambassador-service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
```

**Expected behavior**
Ambassador running

**Versions:**
 - Ambassador: image: quay.io/datawire/ambassador:0.61.0
 - Kubernetes environment rancher running on Azure VM
 - Version 1.13.5

**Additional context**
```bash
kubectl get --raw /k8s/clusters/c-kmw7v/apis/custom.metrics.k8s.io| jq
```
```json
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "custom.metrics.k8s.io",
  "versions": [
    {
      "groupVersion": "custom.metrics.k8s.io/v1beta1",
      "version": "v1beta1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "custom.metrics.k8s.io/v1beta1",
    "version": "v1beta1"
  }
}
```
```bash
kubectl get --raw /k8s/clusters/c-kmw7v/apis/custom.metrics.k8s.io/v1beta1| jq
Error from server (NotFound): the server could not find the requested resource
```

**Comment by richarddli** [comment]
This is an issue with your Kubernetes cluster, not with Ambassador. Retry installing, or double check your cluster setup.

**Comment by aminebizid** [comment]
Solved after uninstalling keda.

**Comment by aminebizid** [comment]
[Keda opened issue](https://github.com/kedacore/keda/issues/225)

**Comment by Sanket110297** [comment]
Possible Solution:
https://stackoverflow.com/questions/62442679/could-not-get-apiversions-from-kubernetes-unable-to-retrieve-the-complete-list
