### ISSUE TITLE
`AMBASSADOR_NO_KUBEWATCH=no_kubewatch` no longer work with Ambassador `0.70.1`

### ISSUE THREAD

**Issue by gsagula** [datawire/ambassador#1592]
**To Reproduce**
1. Start Ambassador with AMBASSADOR_NO_KUBEWATCH=no_kubewatch

**Expected behavior**
Ambassador should not crash with the following:
```
2019-06-03 17:59:39 kubewatch [27 TMainThread] 0.70.1 INFO: No K8s
ambassador_1    | 2019-06-03 17:59:39 kubewatch [27 TMainThread] 0.70.1 ERROR: could not connect to Kubernetes
ambassador_1    | 2019-06-03 17:59:39,603 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c588>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | 2019-06-03 17:59:39 kubewatch [27 TMainThread] 0.70.1 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c588>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | 2019-06-03 17:59:39,604 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c6a0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | 2019-06-03 17:59:39 kubewatch [27 TMainThread] 0.70.1 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c6a0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | 2019-06-03 17:59:39,605 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c748>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | 2019-06-03 17:59:39 kubewatch [27 TMainThread] 0.70.1 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4278c748>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authservices.getambassador.io
ambassador_1    | Traceback (most recent call last):
ambassador_1    |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
ambassador_1    |     (self._dns_host, self.port), self.timeout, **extra_kw)
ambassador_1    |   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
ambassador_1    |     raise err
ambassador_1    |   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
ambassador_1    |     sock.connect(sa)
ambassador_1    | ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by kflynn** [comment]
Dup of #1569. ;)
