### ISSUE TITLE
Diag API json=true returns server error.

### ISSUE THREAD

**Issue by Andrei-Predoiu** [datawire/ambassador#1634]
**Describe the bug**
http://127.0.0.1:8877/ambassador/v0/diag/?json=true
Accessing the diag api does not work in version 0.71 

**To Reproduce**
1.  kubectl port-forward service/ambassador-admin 8877
2. go to http://127.0.0.1:8877/ambassador/v0/diag/?json=true
3. See error

**Expected behavior**
See the tvars as json

**Versions (please complete the following information):**
 - Ambassador: 0.71
 - Kubernetes environment AKS

**Additional context**
Here is the stacktrace:
`2019-06-17 14:45:27 diagd 0.71.0 [P87TThreadPoolExecutor-0_2] ERROR: Object of type 'function' is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 183, in wrapper
    result = f(*args, reqid=reqid, **kwds)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 422, in show_overview
    return jsonify(tvars)
  File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable
2019-06-17 14:45:27 diagd 0.71.0 [P87TThreadPoolExecutor-0_2] ERROR: 85A21DBB-DF16-4B4B-A6C0-245B7C472ABC: 10.228.248.15 "GET /ambassador/v0/diag/" 5ms 500 server error`

**Comment by Andrei-Predoiu** [comment]
Issue is gone in 0.72.0
