### ISSUE TITLE
Invalid mappings can destabilize ambassador and introduce a brittle state

### ISSUE THREAD

**Issue by Andrei-Predoiu** [datawire/ambassador#1635]
**Describe the bug**
Applying an invalid mapping seems to be tolerated fairly fine by ambassador. Actually, as long as the invalid mapping exists, it can throw the gateway into a brittle state where any new ambassador pods will be stuck in a crash loop.

While the invalid mapping exists, ambassador cannot scale or recover.

What is also very concerning, it seems that multiple attempts to apply bad mappings do not generate the same log output. The first attempt will result in an error and stack-trace, the 2nd attempt seems to generate a seemingly irrelevant message saying the following
`2019/06/17 15:18:14 kubebootstrap: found xxx "service" in namespace "*"
2019/06/17 15:18:14 kubebootstrap: sent "service" to 1 receivers`

Third attempt and beyond will not result in any log lines. It does not matter if the same or multiple different broken mappings are applied.

**To Reproduce**
1.  Apply the following mapping:

```
---
apiVersion: v1
kind: Service
metadata:
  name: errored-mapping
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  # ERROR
      prefix: /
      host: errored.config.net
      timeout_ms: 10000
      service: this-is-a-service-maybe:8080
      rewrite: /
      bypass_auth: true
spec:
  ports:
    - name: errored-svc-ambmap
      port: 80
```

2. Check ambassador logs, you should see this:
```
2019/06/17 15:16:51 notify: sh /ambassador/post_watt.sh http://localhost:8002/snapshots/2
2019-06-17 15:16:52 diagd 0.72.0 [P83TThreadPoolExecutor-0_3] INFO: Update requested: watt, http://localhost:8002/snapshots/2
2019-06-17 15:16:52 diagd 0.72.0 [P83TAmbassadorEventWatcher] INFO: copying configuration: watt, http://localhost:8002/snapshots/2 to /ambassador/snapshots/snapshot-tmp.yaml
2019-06-17 15:16:52 diagd 0.72.0 [P83TAmbassadorEventWatcher] ERROR: could not reconfigure: ACResource: Mapping requires name ({'prefix': '/', 'host': 'errored.config.net', 'timeout_ms': 10000, 'service': 'this-is-a-service-maybe:8080', 'rewrite': '/', 'bypass_auth': True})
2019-06-17 15:16:52 diagd 0.72.0 [P83TAmbassadorEventWatcher] ERROR: ACResource: Mapping requires name ({'prefix': '/', 'host': 'errored.config.net', 'timeout_ms': 10000, 'service': 'this-is-a-service-maybe:8080', 'rewrite': '/', 'bypass_auth': True})
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 600, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 708, in load_config_watt
    fetcher.parse_watt(serialization)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/resourcefetcher.py", line 154, in parse_watt
    self.handle_k8s(obj)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/resourcefetcher.py", line 202, in handle_k8s
    filename=self.filename, rkey=rkey)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/resourcefetcher.py", line 259, in parse_object
    self.process_object(obj, rkey=rkey)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/resourcefetcher.py", line 310, in process_object
    r = ACResource.from_dict(rkey, rkey, serialization, obj)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/resource.py", line 196, in from_dict
    return resource_class(rkey, location=location, serialization=serialization, **attrs)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/acresource.py", line 64, in __init__
    raise Exception("ACResource: %s requires name (%s)" % (kind, repr(kwargs)))
Exception: ACResource: Mapping requires name ({'prefix': '/', 'host': 'errored.config.net', 'timeout_ms': 10000, 'service': 'this-is-a-service-maybe:8080', 'rewrite': '/', 'bypass_auth': True})
```
3. Delete the config in step 1 and apply it again, you should see something like this
```
2019/06/17 15:18:14 kubebootstrap: found 31 "service" in namespace "*"
2019/06/17 15:18:14 kubebootstrap: sent "service" to 1 receivers
```

4. Repeat step 3, nothing in logs

5. Keep the bad mapping and delete any of the ambassador pods or scale up the ambassador deployment, notice they are in a restart loop and never ready.

6. Delete the bad mapping. After another restart, the pod from step 5 should be running

**Expected behavior**
I expect that every time a bad mapping is applied, i get the same message in the logs. Hopefully the same message as the one in step 2.

I expect errored mappings to be listed in the ambassador route table or in the notices section of the diagnostics page.

I expect that error-ed mappings do not stop ambassador pods from starting.

**Versions (please complete the following information):**
 - Ambassador: 0.72
 - Kubernetes environment: AKS
 - Version 1.13.5

**Comment by Andrei-Predoiu** [comment]
@kflynn @danielbryantuk  I would start implementing a fix but i'd like to know if you agree with my solution:

1.  Add error handling so the exception is handled as an error, the logs would look like this:
`2019-06-17 15:16:52 diagd 0.72.0 [P83TAmbassadorEventWatcher] ERROR: ACResource: Mapping requires name ({'prefix': '/', 'host': 'errored.config.net', 'timeout_ms': 10000, 'service': 'this-is-a-service-maybe:8080', 'rewrite': '/', 'bypass_auth': True})`

I assume that doing that will fix the brittleness issues since it will stop the exception from bubbling up and killing whatever it is killing right now. This would be the minimum necessary.

2.  Write the error in tvars under errors or notices. If errors don't show properly in diag view, i will put it in notices. I want it to show in the diag page but i don't want to implement new ui for it.

PS:
Adding the broken mapping to the routes table is an improvement that i don't have the time to implement. It involves updating the routes table to show invalid/ errored routes and a reason for why they are in that state.

**Comment by knlambert** [comment]
Same problem here. We are using the gateway to serve differents apps on our Kubernetes cluster, and a wrong configuration makes the whole service unstable.

**Comment by Andrei-Predoiu** [comment]
@kflynn now that the PR has been merged, this can be closed

**Comment by ghostsquad** [comment]
I wish Ambassador was written in something like Go. Error handling is like part of the language, and is easy to find, and know when something _could_ error.
