### ISSUE TITLE
Ambassador fails to generate envoy config after adding a new TLSContext until restart

### ISSUE THREAD

**Issue by LeoHexspoor** [datawire/ambassador#1680]
**Describe the bug**
Anytime I deploy a new TLSContext the envoy configuration process crashes. Ambassador will continue to work with the old configuration. From that point on no new configuration is generated again until I restart the Kubernetes pod. 

If the TLSContext already exists before Ambassador starts it works without any problems. Removing and redeploying TLSContext's that existed before Ambassador started also works without any issue.

**To Reproduce**
1. Deploy secret 'X' with a TLS certificate
2. Start Ambassador with TLS enabled & the default TLS secret does not exist
3. Deploy a TLSContext that references secret 'X'
4. See the following error in the logs
```
2019-07-12 11:06:24 diagd 0.73.0 [P89TAmbassadorEventWatcher] ERROR: could not reconfigure: 'cert_chain_file'
2019-07-12 11:06:24 diagd 0.73.0 [P89TAmbassadorEventWatcher] ERROR: 'cert_chain_file'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 624, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 742, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 756, in _load_ir
    econf = EnvoyConfig.generate(ir, "V2")
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/common.py", line 83, in generate
    return V2Config(ir)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2config.py", line 55, in __init__
    V2Listener.generate(self)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2listener.py", line 741, in generate
    listener = config.save_element('listener', irlistener, V2Listener(config, irlistener))
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2listener.py", line 567, in __init__
    self.handle_sni(config)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2listener.py", line 718, in handle_sni
    sni_value = sni_route['info']['secret_info'][sni_key]
KeyError: 'cert_chain_file'
```
5. Envoy is never reconfigured when new mappings are deployed or existing mappings change until Ambassador is restarted.

**Expected behavior**
I expect to be able to deploy a new TLSContext into Ambassador without having to restart Ambassador.

**Versions (please complete the following information):**
 - Ambassador: 0.73.0 (also reproduced in 0.72.0)
 - Kubernetes environment: GKE
 - Version: 1.13.6-gke.13

**Additional context**
Ambassador is running scoped to a single namespace and is using a specific Ambassador ID.

**Comment by mdgreenwald** [comment]
We are also impacted by this bug.

**Versions:**
Ambassador: 0.85.0
Kubernetes environment: Kops/AWS
Kuberentes Version: v1.13.12
