### ISSUE TITLE
AmbassadorEventWatcher OOM with 0.75.0 

### ISSUE THREAD

**Issue by phsiao** [datawire/ambassador#1883]
**Describe the bug**

AmbassadorEventWatcher OOM and seem to stop watching new service changes.

Some relevant log entries

```
2019-09-30 22:19:50 diagd 0.75.0 [P687TAmbassadorEventWatcher] ERROR: could not reconfigure: [Errno 12] Out of memory
2019-09-30 22:19:50 diagd 0.75.0 [P687TAmbassadorEventWatcher] ERROR: [Errno 12] Out of memory
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 645, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 820, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 827, in _load_ir
    open(aconf_path, "w").write(aconf.as_json())
OSError: [Errno 12] Out of memory
2019/09/30 22:19:50 aggregator: watch hook failed: signal: killed
2019/09/30 22:19:50 aggregator: found 0 kubernetes watches
2019/09/30 22:19:50 aggregator: found 0 consul watches
2019/09/30 22:19:50 kubewatchman: processing 0 kubernetes watch specs
2019/09/30 22:19:50 consulwatchman: processing 0 consul watches
2019/09/30 22:19:51 kubebootstrap: found 2036 "service" in namespace "*"
```

output from top inside the pod

```
Mem: 120882248K used, 471977472K free, 1148544K shrd, 739936K buff, 11741152K cached
CPU:   1% usr   0% sys   0% nic  98% idle   0% io   0% irq   0% sirq
Load average: 1.87 1.25 1.03 2/3713 13034
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  782     1 8888     S    1060m   0%  15   0% envoy -c /ambassador/bootstrap-ads.json
  687   675 8888     S     194m   0%  53   0% {diagd} /usr/bin/python3 /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kic
  696     1 8888     S    5174m   0%  41   0% /ambassador/watt --port 8002 --notify sh /ambassador/post_watt.sh -s service -s AuthService -s Mapping -s Module -s RateLimitService -s TCPMapping -s TLSContext -
  668     1 8888     S     122m   0%  20   0% ambex -ads 8003 /ambassador/envoy
  675     1 8888     S    42080   0%  43   0% {diagd} /usr/bin/python3 /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kic
13020 13017 8888     S    19600   0%  36   0% python3 /ambassador/post_update.py http://localhost:8002/snapshots/997
    1     0 8888     S     2324   0%  18   0% {entrypoint.sh} /bin/bash ./entrypoint.sh
13022     0 8888     S     2316   0%   0   0% bash
13017   696 8888     S     1588   0%  32   0% sh /ambassador/post_watt.sh http://localhost:8002/snapshots/997
13034 13022 8888     R     1528   0%  51   0% top
```

**To Reproduce**

N/A

**Expected behavior**

Should recover from OOM and not become stale.

**Versions (please complete the following information):**
 - Ambassador: 0.75.0
 - Kubernetes environment: bare metal
 - Version 1.13.6

**Additional context**

We have three replicas running at the same time, two ran into this issue, one was ok.  Not sure how to reproduce it.  I delete one of the problem one and it recovers after restart.

**Comment by eterna2** [comment]
I also encounter the exact same issue for all my pods. I think this is an important feature because there is no notification at all. The issue is only discovered when I tried to deploy a new service.

**Comment by tribonacci** [comment]
I also faced a similar recently where "EventWatcher" was not running since 5days. 
So, iPs started getting stale in envoy.json. 
Ambassador wasn't showing errors or crashes.
