### ISSUE TITLE
Ambassador does not start

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#224]
```
./entrypoint.sh: set: line 63: can't access tty; job control turned off
INFO:kubewatch:Merging config inputs from /etc/ambassador-config
2018-01-19 22:22:12,792 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
2018-01-19 22:22:12,793 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
2018-01-19 22:22:12,794 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/application/kubewatch.py", line 488, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 471, in main
    sync(restarter)
  File "/application/kubewatch.py", line 309, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-pa
```

**Comment by richarddli** [comment]
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(
1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)'),)': /api/v1/namespaces/default/configmaps
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
conn.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
sslcontext=context)
File "/usr/lib/python3.6/site-packages/urllib3/util/ssl.py", line 329, in ssl_wrap_socket
return context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
_context=self, _session=session)
File "/usr/lib/python3.6/ssl.py", line 814, in init
self.do_handshake()
File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
self._sslobj.do_handshake()
File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)
```

**Comment by karlmutch** [comment]
The earlier 0.22.0 version gives an openssl error which appears to be related to scout:

./entrypoint.sh: set: line 63: can't access tty; job control turned off
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verificat
ion is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: Merging config inputs from /etc/ambassador-config
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: Changes detected, regenerating envoy config.
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: generating config with gencount 1
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: CLUSTER cluster_127_0_0_1_8877: new from --internal--
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: CLUSTER cluster_127_0_0_1_8877: referenced by --internal--
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: CLUSTER cluster_127_0_0_1_8877: referenced by --internal--
2018-01-20 17:46:44 kubewatch 0.22.0 WARNING: Scout: could not post report: HTTPSConnectionPool(host='kubernaut.io', port=443): Max retries exceeded with ur
l: /scout (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:777)'),))
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: Scout reports {"latest_version": "0.22.0", "exception": "could not post report: HTTPSConnectionPool(host='kuberna
ut.io', port=443): Max retries exceeded with url: /scout (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:777)'),))", "cach
ed": false, "timestamp": 1516470404.158132}
[2018-01-20 17:46:44.275][9][info][upstream] source/common/upstream/cluster_manager_impl.cc:130] cm init: all clusters initialized
[2018-01-20 17:46:44.275][9][info][config] source/server/configuration_impl.cc:46] loading 1 listener(s)
[2018-01-20 17:46:44.282][9][info][config] source/server/configuration_impl.cc:84] loading tracing configuration
[2018-01-20 17:46:44.283][9][info][config] source/server/configuration_impl.cc:110] loading stats sink configuration
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: Configuration /etc/ambassador-config-1-envoy.json valid
2018-01-20 17:46:44 kubewatch 0.22.0 INFO: Moved valid configuration /etc/ambassador-config-1-envoy.json to /etc/envoy-1.json
AMBASSADOR: starting diagd

**Comment by richarddli** [comment]
The scout errors should be harmless. I'm not running into this issue any more, but I do see the issues in #240 so going to close this ticket for now.
