### ISSUE TITLE
After Azure AKS certificate rotation the Ambassador pod can not start

### ISSUE THREAD

**Issue by attilajanko** [datawire/ambassador#2972]
**Describe the bug**
We had an expired certificate in our Azure AKS cluster, and did a certificate rotation on the cluster with this documentation: https://docs.microsoft.com/en-us/azure/aks/certificate-rotation, after this task ran successfully, all of our services can restart and running state, only our ambassador pods are have Error,CrashLoopBackOff

**To Reproduce**
1. Go to Azure portal, login to the subscription via PowerShell, run the az aks rotate-certs -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME command
2. Get the new kubernetes config 
3. kubectl get pods -n core | grep ambassador
4. ambassador-65bd984995-7qgh8                                  0/1     CrashLoopBackOff   4          2m51s
ambassador-65bd984995-bpnv2                                  0/1     CrashLoopBackOff   4          3m1s
ambassador-65bd984995-lmwgb                                  0/1     CrashLoopBackOff   4          2m51s

**Expected behavior**
Ambassador pod in running state.

**Versions (please complete the following information):**
 - Ambassador: 1.5.2
 - Kubernetes environment Azure AKS
 - Version 1.16.7

**Additional context**

**Comment by attilajanko** [comment]
`2020-09-10 10:40:34 kubewatch [9 TMainThread] 1.5.2 DEBUG: looking up ID for namespace default
2020-09-10 10:40:34,997 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:34 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:35,015 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:35 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:35,026 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:35 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 358, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 367, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 233, in main
    ret = v1.read_namespace(wanted)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 17572, in read_namespace
    (data) = self.read_namespace_with_http_info(name, **kwargs)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 17657, in read_namespace_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)')))
2020-09-10 10:40:35 AMBASSADOR INFO could not determine cluster-id; exiting
[ajankoki@t-jumpbox ~]$ watch kubectl_aks get pods -n core
[ajankoki@t-jumpbox ~]$ kubectl_aks logs -n core -f ambassador-8494c95dd5-pgxgg
2020-09-10 10:40:48 kubewatch [9 TMainThread] 1.5.2 DEBUG: looking up ID for namespace default
2020-09-10 10:40:48,287 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:48 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:48,299 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:48 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:48,317 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
2020-09-10 10:40:48 kubewatch [9 TMainThread] 1.5.2 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)'))': /api/v1/namespaces/default
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 358, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 367, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 233, in main
    ret = v1.read_namespace(wanted)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 17572, in read_namespace
    (data) = self.read_namespace_with_http_info(name, **kwargs)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 17657, in read_namespace_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)')))
2020-09-10 10:40:48 AMBASSADOR INFO could not determine cluster-id; exiting

`

**Comment by attilajanko** [comment]
This problem maybe solved via add the AMBASSADOR_VERIFY_SSL_FALSE: true to the deployment file

**Comment by attilajanko** [comment]
But after we getting a new error:
`2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: looking up ID for namespace default
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: cluster ID URL is d6e_id://316642a2-d794-11e8-bd00-c2f24d47ed93/default
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: IngressClass check got 404
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: Ambassador does not have permission to read IngressClass resources. To enable IngressClass support, configure RBAC to allow Ambassador to read IngressClass resources, then restart the Ambassador pod.
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: CRD type definition not found for ambassadorinstallations.getambassador.io
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: ambassadorinstallations.getambassador.io CRD not available
2020-09-10 12:24:09 kubewatch [9 TMainThread] 1.7.0 DEBUG: cluster ID is 380a144a-8c82-5f5f-b0fa-09d2f16340cd (from namespace default)
2020-09-10 12:24:10 AMBASSADOR INFO starting with environment:
2020-09-10 12:24:10 AMBASSADOR INFO ====
AMBASSADOR_ADMIN_PORT=tcp://192.168.148.121:8877
AMBASSADOR_ADMIN_PORT_8877_TCP=tcp://192.168.148.121:8877
AMBASSADOR_ADMIN_PORT_8877_TCP_ADDR=192.168.148.121
AMBASSADOR_ADMIN_PORT_8877_TCP_PORT=8877
AMBASSADOR_ADMIN_PORT_8877_TCP_PROTO=tcp
AMBASSADOR_ADMIN_SERVICE_HOST=192.168.148.121
AMBASSADOR_ADMIN_SERVICE_PORT=8877
AMBASSADOR_ADMIN_SERVICE_PORT_AMBASSADOR_ADMIN=8877
AMBASSADOR_ADMIN_URL=http://127.0.0.1:8877
AMBASSADOR_CLUSTER_ID=380a144a-8c82-5f5f-b0fa-09d2f16340cd
AMBASSADOR_CONFIG_BASE_DIR=/ambassador
AMBASSADOR_INTERNAL_URL=https://127.0.0.1:8443
AMBASSADOR_NAMESPACE=core
AMBASSADOR_PORT=tcp://192.168.109.88:80
AMBASSADOR_PORT_80_TCP=tcp://192.168.109.88:80
AMBASSADOR_PORT_80_TCP_ADDR=192.168.109.88
AMBASSADOR_PORT_80_TCP_PORT=80
AMBASSADOR_PORT_80_TCP_PROTO=tcp
AMBASSADOR_REDIS_PORT=tcp://192.168.155.177:6379
AMBASSADOR_REDIS_PORT_6379_TCP=tcp://192.168.155.177:6379
AMBASSADOR_REDIS_PORT_6379_TCP_ADDR=192.168.155.177
AMBASSADOR_REDIS_PORT_6379_TCP_PORT=6379
AMBASSADOR_REDIS_PORT_6379_TCP_PROTO=tcp
AMBASSADOR_REDIS_SERVICE_HOST=192.168.155.177
AMBASSADOR_REDIS_SERVICE_PORT=6379
AMBASSADOR_SERVICE_HOST=192.168.109.88
AMBASSADOR_SERVICE_PORT=80
AMBASSADOR_SERVICE_PORT_HTTP=80
AMBASSADOR_URL=https://ambassador.core.svc.cluster.local
AMBASSADOR_VERIFY_SSL_FALSE=true
2020-09-10 12:24:10 AMBASSADOR INFO ====
2020-09-10 12:24:10 AMBASSADOR INFO launching worker process 'ambex': 'ambex' '--ads-listen-address=127.0.0.1:8003' '/ambassador/envoy'
2020-09-10 12:24:10 AMBASSADOR INFO ambex is PID 75
2020-09-10 12:24:10 AMBASSADOR INFO launching worker process 'diagd': 'diagd' '/ambassador/snapshots' '/ambassador/bootstrap-ads.json' '/ambassador/envoy/envoy.json' '--notices' '/ambassador/notices.json' '--kick' 'kill -HUP 1'
2020-09-10 12:24:10 AMBASSADOR INFO diagd is PID 78
2020-09-10 12:24:11 diagd 1.7.0 [P78TMainThread] INFO: AMBASSADOR_FAST_RECONFIGURE disabled, not initializing cache
2020-09-10 12:24:11 diagd 1.7.0 [P78TMainThread] INFO: WILL NOT update Mapping status
2020-09-10 12:24:11 diagd 1.7.0 [P78TMainThread] INFO: thread count 17, listening on 0.0.0.0:8877
2020-09-10 12:24:12 diagd 1.7.0 [P78TMainThread] INFO: Ambassador 1.7.0 booted
[2020-09-10 12:24:12 +0000] [78] [INFO] Starting gunicorn 20.0.4
[2020-09-10 12:24:12 +0000] [78] [INFO] Listening at: http://0.0.0.0:8877 (78)
[2020-09-10 12:24:12 +0000] [78] [INFO] Using worker: threads
[2020-09-10 12:24:12 +0000] [97] [INFO] Booting worker with pid: 97
2020-09-10 12:24:12 diagd 1.7.0 [P97TAEW] INFO: starting Scout checker and timer logger
2020-09-10 12:24:12 diagd 1.7.0 [P97TAEW] INFO: starting event watcher
2020-09-10 12:24:13 AMBASSADOR INFO diagd running
2020-09-10 12:24:13 AMBASSADOR INFO launching worker process 'watt': 'watt' '--listen-address=127.0.0.1:8002' '--notify' 'python /ambassador/post_update.py --watt ' '--watch' 'python /ambassador/watch_hook.py' '-s' 'service' '-s' 'ingresses' '-s' 'AuthService' '-s' 'Mapping' '-s' 'Module' '-s' 'RateLimitService' '-s' 'TCPMapping' '-s' 'TLSContext' '-s' 'TracingService' '-s' 'ConsulResolver' '-s' 'KubernetesEndpointResolver' '-s' 'KubernetesServiceResolver' '-s' 'Host' '-s' 'LogService'
2020-09-10 12:24:13 AMBASSADOR INFO watt is PID 107
2020-09-10 12:24:13 AMBASSADOR INFO launching worker process 'amb-sidecar': '/ambassador/sidecars/amb-sidecar'
2020-09-10 12:24:13 AMBASSADOR INFO amb-sidecar is PID 114
time="2020-09-10T12:24:13Z" level=info msg="starting watt..."
time="2020-09-10 12:24:13" level=info msg="Ambassador Edge Stack configuration loaded" func=github.com/datawire/apro/cmd/amb-sidecar/runner.runE file="github.com/datawire/apro/cmd/amb-sidecar/runner/main.go:142"
2020/09/10 12:24:13 api: snapshot server listening on: tcp:127.0.0.1:8002
2020/09/10 12:24:13 kubebootstrap: ERROR: Get "https://192.168.0.1:443/api?timeout=32s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
2020/09/10 12:24:13 consulwatchman: signaling shutdown
2020/09/10 12:24:13 kubewatchman: signaling shutdown
2020/09/10 12:24:13 aggregator: signaling shutdown
2020/09/10 12:24:13 invoker: signaling shutdown
2020/09/10 12:24:13 api: signaling shutdown
2020/09/10 12:24:13 consulwatchman: exited
2020/09/10 12:24:13 kubewatchman: exited
2020/09/10 12:24:13 aggregator: exited
2020/09/10 12:24:13 invoker: shutdown initiated
2020/09/10 12:24:13 invoker: exited
2020/09/10 12:24:14 api: exited
time="2020-09-10T12:24:14Z" level=error msg="ERROR(s): kubebootstrap: Get \"https://192.168.0.1:443/api?timeout=32s\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"ca\")"
/buildroot/ambassador/python/entrypoint.sh: line 26: warning: run_pending_traps: bad value in trap_list[17]: 0x558f6fc4edd3
/buildroot/ambassador/python/entrypoint.sh: line 23: warning: run_pending_traps: bad value in trap_list[17]: 0x558f6fc4edd3
2020-09-10 12:24:14 AMBASSADOR INFO watt exited with status 1
/buildroot/ambassador/python/entrypoint.sh: line 23: warning: run_pending_traps: bad value in trap_list[17]: 0x558f6fc4edd3
2020-09-10 12:24:14 AMBASSADOR INFO killing extant processes
kill: can't kill pid 107: No such process
/buildroot/ambassador/python/entrypoint.sh: line 215: warning: run_pending_traps: bad value in trap_list[17]: 0x558f6fc4edd3
[2020-09-10 12:24:14 +0000] [78] [INFO] Handling signal: term
/buildroot/ambassador/python/entrypoint.sh: line 23: warning: run_pending_traps: bad value in trap_list[17]: 0x558f6fc4edd3
2020-09-10 12:24:14 AMBASSADOR INFO shutting down (1)
`

**Comment by attilajanko** [comment]
Was maybe Azure related problem, seems it is solved now
![image](https://user-images.githubusercontent.com/29592587/92743041-7dca6100-f380-11ea-8ee2-fe8db0589e92.png)
