### ISSUE TITLE
Ambassador cannot work with MagicDNS in Knative

### ISSUE THREAD

**Issue by benjaminhuo** [datawire/ambassador#3038]
**Describe the bug**
default-domain-xxx pod keeps crashing when using ambassador as knative gateway

**To Reproduce**
1. Install knative serving and ambassador following https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component
2. Install MagicDNS support following following https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component by `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.18.0/serving-default-domain.yaml
`
3. The default-domain-xxx pod keeps crashing and found below error  logs： 
```bash
kubectl -n knative-serving logs default-domain-k25pv 
W1022 08:30:21.290614       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x158b7ff]

goroutine 1 [running]:
main.findGatewayAddress(0x1cbc7c0, 0xc00042a000, 0xc0003a6160, 0xc000242ee0, 0x0, 0x0, 0x0)
	knative.dev/serving/cmd/default-domain/main.go:135 +0x75f
main.main()
	knative.dev/serving/cmd/default-domain/main.go:197 +0x994
```

**Expected behavior**
Ambassador should work with MagicDNS without problems

**Versions (please complete the following information):**
 - Ambassador: v1.8.1
 - Kubernetes environment: Installed by kubeadm
 - Version 1.18.6

**Comment by nak3** [comment]
For more detail, the `ingress.status.LoadBalancer` status field in Knative Ingress was deprecated by https://github.com/knative/networking/commit/730b2ab8639b39f4559f34916ba67307f8458a04.

But it seems ambassador still uses it https://github.com/datawire/ambassador/blob/0fcc86d0ea7557245d3e31eb2ae21c9129d43922/python/ambassador/fetch/knative.py#L129. It should use `ingress.status.PublicLoadBalancer` instead.

**Comment by benjaminhuo** [comment]
Is there any update on this @kflynn @richarddli @LukeShu
