### ISSUE TITLE
Ambassador with AuthService and TracingService of the same name crashes on startup

### ISSUE THREAD

**Issue by jasons42** [datawire/ambassador#3174]
**Describe the bug**
When configured with an AuthService and TracingService of the same name (e.g., "test-ambassador"), Ambassador crashes on startup.

Stack trace:
`2021-01-19 21:10:30 diagd 1.10.0 [P48TAEW] ERROR: could not reconfigure: 'NoneType' object has no attribute 'envoy_name'
2021-01-19 21:10:30 diagd 1.10.0 [P48TAEW] ERROR: 'NoneType' object has no attribute 'envoy_name'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1302, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1461, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1536, in _load_ir
    ir = IR(aconf, secret_handler=secret_handler, cache=self.app.cache)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/ir.py", line 362, in __init__
    self.tracing.finalize()
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irtracing.py", line 120, in finalize
    self.ir.logger.debug("tracing cluster envoy name: %s" % self.cluster.envoy_name)
AttributeError: 'NoneType' object has no attribute 'envoy_name'
2021/01/19 21:10:30 error notifying diagd: 500 INTERNAL SERVER ERROR, configuration`

**To Reproduce**
1. Apply an AuthService and TracingService manifest with the same name (e.g., test-ambassador)
2. Deploy Ambassador
3. See pods crashlooping

**Expected behavior**
Ambassador should startup cleanly with both the AuthService and TracingService activated.

**Versions (please complete the following information):**
 - Ambassador: 1.10.0, 1.5.1
 - Kubernetes environment: bare metal and Minikube
 - Version: bare metal 1.17.3, minikube 1.18.0

**Comment by cindymullins-dw** [comment]
Interesting catch but it also seems reasonable these services could be easily differentiated by different names.  Is the error on the Envoy side or on the Ambassador side?

**Comment by jasons42** [comment]
@cindymullins-dw The error appears to be generated from the Ambassador side, specifically diagd.

Using different names works, but it's not something I would expect to need to do, in particular as the default behaviour of the official Helm chart is to use the same name for all relevant resources. We use that pattern for all additional Ambassador resources, and in fact for all services we run in our k8s environment (except in cases where multiple resources of the same type are required). I think this is a pretty standard practice in k8s in most orgs.

It's also not obvious from the error message what the problem is. It could take a fair bit of trial and error to figure out out.

**Comment by jasons42** [comment]
Ran into this issue again while upgrading to 2.5.1 so the bug is still present. Again it is pretty well impossible to tell what the problem is from the logs alone.
