### ISSUE TITLE
Ambassador Tutorial without RBAC Broken with Latest Minikube on Mac

### ISSUE THREAD

**Issue by Jon-Schneider** [datawire/ambassador#393]
The [Deploying Ambassador to Kubernetes](https://www.getambassador.io/user-guide/getting-started?q=) Tutorial no-RBAC path does not appear to work on Mac.

I've run this on two seperate Macs today. As far as I can tell the configs completely identical except for the git versions.

####Versions
Mac 10.13.4. I've tested on two seperate Macs with the same configs.
Docker (Mac) Version 18.03.0-ce-mac60 (23751)
minikube version: v0.26.1
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

#### Repro Log
**minikube delete**
[uninstalled and renstalled docker, minikube and virtualbox casks]
**minikube start**
**kubectl apply -f ambassador-service.yaml**  
`service "ambassador" created`
**kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-no-rbac.yaml**

```
service "ambassador-admin" created
deployment.extensions "ambassador" created
```

This results in the Ambassador pods in a crash loop, continually restartng and resulting in a status of CrashLoopBackOff.

**kubectl logs ambassador-6bf7788f7b-8bm94 ambassador**

```
./entrypoint.sh: set: line 65: can't access tty; job control turned off
Traceback (most recent call last):
  File "/application/kubewatch.py", line 493, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 476, in main
    sync(restarter)
  File "/application/kubewatch.py", line 313, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 26 Apr 2018 03:51:08 GMT', 'Content-Length': '269'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:default:default\" cannot list configmaps in the namespace \"default\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```

**Comment by richarddli** [comment]
The proximate cause of this appears to be a permission error -- Ambassador can't do `ConfigMap` operations in the `default` namespace.

* Are you trying to do everything in `default`?
* Do you know if Minikube has added RBAC by default in the latest versions? (Last time I checked, this was not the case.)

**Comment by Jon-Schneider** [comment]
It does not appear Ambassador has made RBAC default. You still need to pass in `--extra-config=apiserver.authorization-mode=RBAC` to use it.

I tried making a new namespace and running from it and I'm still having this issue:

**ambassador-namespace.yaml**
```
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador-ns

```

```
JonsMacbookPro2017:ambassador-demo jon$ kubectl get po
kNo resources found.
JonsMacbookPro2017:ambassador-demo jon$ kubectl get ns
NAME          STATUS    AGE
default       Active    17s
kube-public   Active    13s
kube-system   Active    17s
JonsMacbookPro2017:ambassador-demo jon$ kubectl apply -f ambassador-namespace.yaml 
namespace "ambassador-ns" created
JonsMacbookPro2017:ambassador-demo jon$ kubectl get ns
NAME            STATUS    AGE
ambassador-ns   Active    1m
default         Active    2m
kube-public     Active    2m
kube-system     Active    2m
JonsMacbookPro2017:ambassador-demo jon$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/jon/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/jon/.minikube/client.crt
    client-key: /Users/jon/.minikube/client.key
JonsMacbookPro2017:ambassador-demo jon$  kubectl config set-context dev --namespace=ambassador-ns --cluster=minikube --user=minikube
Context "dev" created.
JonsMacbookPro2017:ambassador-demo jon$ kubectl config use-context dev
Switched to context "dev".
JonsMacbookPro2017:ambassador-demo jon$ kubectl get deployment
No resources found.
JonsMacbookPro2017:ambassador-demo jon$ kubectl get pods
No resources found.
JonsMacbookPro2017:ambassador-demo jon$ ls
ambassador-namespace.yaml	ambassador-service.yaml		development-ns.json		kube-dns-svc.yaml
ambassador-no-rbac.yaml		busybox.yaml			kube-dns-rc.yaml		qotm.yaml
JonsMacbookPro2017:ambassador-demo jon$ kubectl apply -f ambassador-service.yaml 
service "ambassador" created
JonsMacbookPro2017:ambassador-demo jon$ watch kubectl get po
JonsMacbookPro2017:ambassador-demo jon$ watch kubectl get s
JonsMacbookPro2017:ambassador-demo jon$ kubectl get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
ambassador   LoadBalancer   10.100.22.139   <pending>     80:30518/TCP   20s
JonsMacbookPro2017:ambassador-demo jon$ kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-no-rbac.yaml
service "ambassador-admin" created
deployment.extensions "ambassador" created
JonsMacbookPro2017:ambassador-demo jon$ kubectl log ambassador-6bf7788f7b-lrc4l ambassador
log is DEPRECATED and will be removed in a future version. Use logs instead.
./entrypoint.sh: set: line 65: can't access tty; job control turned off
Traceback (most recent call last):
  File "/application/kubewatch.py", line 493, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 476, in main
    sync(restarter)
  File "/application/kubewatch.py", line 313, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 26 Apr 2018 22:37:17 GMT', 'Content-Length': '281'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:ambassador-ns:default\" cannot list configmaps in the namespace \"ambassador-ns\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```

**Comment by Jon-Schneider** [comment]
For whatever reason, starting minikube with `minikube start` and applying the RBAC deploy of Ambassador with `kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml` works correctly even though minikube was not started with RBAC. According to https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md you should have to explicitly enable RBAC.
