### ISSUE TITLE
Deploying Ambassador to Kubernetes from getting started guide fails

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#496]
**Describe the bug**
I was trying out deploying Ambassador to Kubernetes using https://www.getambassador.io/user-guide/getting-started, but my pods fail to come up.

**To Reproduce**
- `kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-no-rbac.yaml`
-
```console
$ kubectl get pods
NAME                          READY     STATUS             RESTARTS   AGE
ambassador-7d95446b76-b5z2t   1/2       CrashLoopBackOff   10         31m
ambassador-7d95446b76-g6dt7   1/2       CrashLoopBackOff   10         31m
ambassador-7d95446b76-pljv4   1/2       CrashLoopBackOff   10         31m
```
-
```console
$ kubectl logs ambassador-7d95446b76-b5z2t -c ambassador
Traceback (most recent call last):
  File "/application/kubewatch.py", line 493, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 476, in main
    sync(restarter)
  File "/application/kubewatch.py", line 313, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 07 Jun 2018 13:07:43 GMT', 'Content-Length': '269'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:default:default\" cannot list configmaps in the namespace \"default\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```

**Expected behavior**
Well, it should work :)

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
`datawire/ambassador:0.34.1`
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version
minikube version: v0.27.0
```

**Comment by containscafeine** [comment]
Turns out minikube comes with RBAC enabled by default now, thanks for pointing that out @richarddli 
This was fixed once I deployed ambassador with RBAC -
`kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml`

**Comment by containscafeine** [comment]
Docs have been added for checking if RBAC is enabled
