### ISSUE TITLE
Ambassador crashes when annotation has empty config

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#497]
**To Reproduce**

```
apiVersion: v1
kind: Service
metadata:
  name: qotm
  annotations:
    getambassador.io/config: |
      ---
spec:
  type: ClusterIP
  selector:
    app: qotm
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
```

**Expected behavior**
An error message, or at least not a crash.

You get:

```
2018-06-07 15:03:03 kubewatch 0.34.1 INFO: generating config with gencount 1 (3 changes)
Traceback (most recent call last):
  File "/application/kubewatch.py", line 493, in &lt;module&gt;
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 476, in main
    sync(restarter)
  File "/application/kubewatch.py", line 373, in sync
    restarter.restart()
  File "/application/kubewatch.py", line 118, in restart
    config = self.generate_config(output)
  File "/application/kubewatch.py", line 151, in generate_config
    aconf = Config(output)
  File "/usr/lib/python3.6/site-packages/ambassador-0.34.1-py3.6.egg/ambassador/config.py", line 336, in __init__
  File "/usr/lib/python3.6/site-packages/ambassador-0.34.1-py3.6.egg/ambassador/config.py", line 414, in process_all_objects
AttributeError: 'NoneType' object has no attribute 'get'
AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```

**Comment by containscafeine** [comment]
Fixed in #691, test in #710
