### ISSUE TITLE
traceback from clean install on an empty minikube cluster

### ISSUE THREAD

**Issue by rhs** [datawire/ambassador#51]
I've included the logs below. The deployment goes into the CrashLoopBackoff and never seems to come alive... I see this in the logs...

```
[rhs@venture ambassador]$ kubectl logs ambassador-381468975-trd2g ambassador 
/application
[2017-05-04 01:20:23.017][9][warning][main] initializing epoch 0 (hot restart version=7.2490552)
[2017-05-04 01:20:23.030][9][warning][main] all clusters initialized. initializing init manager
[2017-05-04 01:20:23.034][9][warning][main] all dependencies initialized. starting workers
[2017-05-04 01:20:23.034][9][warning][main] starting main dispatch loop
2017-05-04 01:20:23 ambassador 0.8.0 INFO: initializing on ambassador-381468975-trd2g (resolved 172.17.0.5)
2017-05-04 01:20:43 ambassador 0.8.0 INFO: ambassador found restarter PID 6
Traceback (most recent call last):
  File "/application/ambassador.py", line 489, in <module>
    main()
  File "/application/ambassador.py", line 475, in main
    new_config(envoy_restarter_pid = -1)    # Don't automagically signal here.
  File "/application/ambassador.py", line 303, in new_config
    num_mappings = len(rc.mappings)
TypeError: object of type 'NoneType' has no len()
```

**Comment by rhs** [comment]
I managed to root cause this to dns mysteriously not functioning in my minikube cluster, but it took a few patches to get enough info to debug the situation...
[debug.txt](https://github.com/datawire/ambassador/files/975182/debug.txt)

I'm pretty sure the exception and behavior of the patch implies something is messed up somewhere (the rc object seems to have evaluated as True despite representing an error).
