### ISSUE TITLE
ValueError: unable to generate config

### ISSUE THREAD

**Issue by damianesteban** [datawire/ambassador#549]
**Describe the bug**

I am getting the following error when deploy Ambassador `v0.21.2`:

```
Traceback (most recent call last):
  File "/application/kubewatch.py", line 480, in &lt;module&gt;
    main()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 463, in main
    sync(restarter)
  File "/application/kubewatch.py", line 361, in sync
    restarter.restart()
  File "/application/kubewatch.py", line 117, in restart
    config = self.generate_config(output)
  File "/application/kubewatch.py", line 163, in generate_config
    raise ValueError("Unable to generate config")
ValueError: Unable to generate config
2018-06-24 23:39:13 AMBASSADOR: kubewatch sync exited with status 1
2018-06-24 23:39:13 AMBASSADOR: Here's the envoy.json we were trying to run with:
ls: cannot access /etc/envoy*.json: No such file or directory
2018-06-24 23:39:13 AMBASSADOR: No config generated.
2018-06-24 23:39:13 AMBASSADOR: shutting down
```

**To Reproduce**

When I deploy ambassador via:

```
$ kubectl apply -f ambassador_service.yaml
```

I can see these errors in the logs.  

**Expected behavior**

Amassador has been working flawlessly for me up until about a week ago.

**Versions (please complete the following information):**
 - Ambassador: 0.21.2
 - Kubernetes environment: Minikube
 - Version: v0.25.0

**Additional context**

**Comment by richarddli** [comment]
Is there any way for you to try reproducing this on the latest version of Ambassador? 0.21 is dozens of releases old, and we've made a lot of improvements/fixes to this area of the code since then.

**Comment by damianesteban** [comment]
Oh wow, I didn't realize I was using such an old version. I'll fire this up with the new version and get back to you shortly.

**Comment by damianesteban** [comment]
I'm not getting the following error on `v0.34.3`:

```
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/application/kubewatch.py", line 495, in main
    sync(restarter)
  File "/application/kubewatch.py", line 320, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12395, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12497, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 26 Jun 2018 00:09:53 GMT', 'Content-Length': '269'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:default:default\" cannot list configmaps in the namespace \"default\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
 AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /etc/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down
```

Again, everything was working perfectly fine up until a few days ago.

**Comment by richarddli** [comment]
Do you mean now, versus not?

Looking more closely, I think this is likely an RBAC error. Did you upgrade your Minikube recently? Are you using the RBAC or non-RBAC YAML? (Minikube enabled RBAC by default, I believe, in a relatively recent release.)

**Comment by damianesteban** [comment]
It was an RBAC issue - I was using the non-RBAC template. Thanks for working through that with me.
