### ISSUE TITLE
Routing does not work - ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#554]
**Describe the bug**
2 users have reported this bug on our slack in 24 hours.

> Hi, I’m just starting using Ambassador and I do have an issue, which I think might be RBAC related but I can’t figure it out. My ambassador pod is throwing me the following messages and none of my routes are working.

Error from user 1 looks like -
```
2018-06-26 14:21:34 kubewatch 0.34.3 ERROR: could not watch for Kubernetes service changes
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/application/kubewatch.py", line 504, in main
    watch_loop(restarter)
  File "/application/kubewatch.py", line 404, in watch_loop
    for evt in watched:
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 117, in stream
    for line in iter_resp_lines(resp):
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 45, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

Error from user 2 looks like -
```
ERROR: could not watch for Kubernetes service changes
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 543, in _update_chunk_length
   self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
   yield
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 598, in read_chunked
   self._update_chunk_length()
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 547, in _update_chunk_length
   raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/application/kubewatch.py", line 484, in main
   watch_loop(restarter)
 File "/application/kubewatch.py", line 386, in watch_loop
   for evt in watched:
 File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 117, in stream
   for line in iter_resp_lines(resp):
 File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 45, in iter_resp_lines
   for seg in resp.read_chunked(decode_content=False):
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
   self._original_response.close()
 File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
   self.gen.throw(type, value, traceback)
 File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
   raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2018-06-26 10:49:41 kubewatch 0.30.1 ERROR: could not watch for Kubernetes service changes
```

User 1 is on ambassador 0.34.3 while user 2 is on ambassador 0.30.1
User 1 says -
```console
$ k version                                                                                                                      (☸ |testbuildcluster)
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
The YAML user 1 is using looks like -
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
  namespace: ambassador
spec:
  type: NodePort
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: 8877
  selector:
    service: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
  namespace: ambassador
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["create", "update", "patch", "get", "list", "watch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
  namespace: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: ambassador
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
  namespace: ambassador
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador
    spec:
      serviceAccountName: ambassador
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.34.3
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: statsd
        image: quay.io/datawire/statsd:0.34.3
      restartPolicy: Always
```

- **Both the users are on Kubernetes v1.9.6**
- **The ambassador pods are in running state for both the user, but these python errors are continuously being logged and routes do not work**

**Comment by containscafeine** [comment]
I've tried reproducing this, but failed -

> Strange, I'm unable to reproduce this with Kube v1.9.6 on GKE -
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Unable to reproduce it on minikube either -
```console
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ofcourseican** [comment]
I'm user 1 in this case. Please let me know if I can help with anything.

**Comment by containscafeine** [comment]
@richarddli pointed out in slack that this is possibly related to https://github.com/kubernetes-client/python/issues/540

**Comment by ofcourseican** [comment]
Fyi: I just upgraded the cluster to v.1.10.3. Still the same problem. So it might not have anything todo with the Kubernetes version.

**Comment by lrodriguez2002cu** [comment]
Any update on this. I am also getting this error. So Ambassador is unable to update the configuration from the annotations present in other services.

**Comment by nmatsui** [comment]
I tried to bypass this ProtocolError. As far as I tried, it seems to be working fine.

https://github.com/datawire/ambassador/pull/724

**Comment by derekperkins** [comment]
I have the same problem. I'm running on AKS 1.10.5.

**Comment by dennis27** [comment]
We are seeing this with AKS 1.9.6 without RBAC
