### ISSUE TITLE
Issue in having two ambassador 

### ISSUE THREAD

**Issue by Harishkrishna17** [datawire/ambassador#610]
```
Error : 018-07-11 07:26:59 kubewatch 0.35.2 INFO: generating config with gencount 1 (1 change)
/usr/lib/python3.6/site-packages/pkg_resources/__init__.py:1298: UserWarning: /ambassador is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
 warnings.warn(msg, UserWarning)
Traceback (most recent call last):
 File "/ambassador/kubewatch.py", line 528, in <module>
   main()
 File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/ambassador/kubewatch.py", line 508, in main
   sync(restarter)
 File "/ambassador/kubewatch.py", line 405, in sync
   restarter.restart()
 File "/ambassador/kubewatch.py", line 133, in restart
   config = self.generate_config(output)
 File "/ambassador/kubewatch.py", line 166, in generate_config
   aconf = Config(output)
 File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 350, in __init__
 File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 448, in process_all_objects
AttributeError: 'NoneType' object has no attribute 'get'
AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /ambassador/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down (1)
```

Deployment Config for ambassador 👍 
```
ApiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: ambassador
spec:
 replicas: 3
 template:
   metadata:
     annotations:
       sidecar.istio.io/inject: "false"
     labels:
       service: ambassador
   spec:
     serviceAccountName: ambassador
     containers:
     - name: ambassador
       image: quay.io/datawire/ambassador:0.35.2
       resources:
         limits:
           cpu: 1
           memory: 400Mi
         requests:
           cpu: 200m
           memory: 100Mi
       env:
       - name: AMBASSADOR_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       - name: AMBASSADOR_ID
         value: ambassador-1
       livenessProbe:
         httpGet:
           path: /ambassador/v0/check_alive
           port: 8877
         initialDelaySeconds: 30
         periodSeconds: 3
```

Configuration of my mappings 👍 
```
     apiVersion: ambassador/v0
     kind: Mapping
     name: test
     ambassador_id: ambassador-1
     prefix: /api/v2
     rewrite: ""
     service: test
```

I am not able to start the ambassador Now , it is going to crashloopbackoff , I am not able to continue with having 2 ambassadors , Please help me out

**Comment by containscafeine** [comment]
I tried replicating with 2 mappings per ambassador, and 2 ambassadors, but I could not replicate the issue. Need more info to replicate -

```yaml
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      ambassador_id: ambassador-2
      name:  qotm_mapping
      prefix: /qotm/
      service: qotm
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      ambassador_id: ambassador-2
      name:  qotm_mapping_2
      prefix: /qotm-2/
      service: qotm
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      ambassador_id: ambassador-1
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      ambassador_id: ambassador-1
      name:  httpbin_mapping_2
      prefix: /httpbin-2/
      service: httpbin.org:80
      host_rewrite: httpbin.org
```

Tried both, on 0.35.2 and 0.35.3

**Comment by containscafeine** [comment]
FWIW, the user had an extra YAML document separator in the config, leading to failure -
```yaml
    ```getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: rm-auth-empmobile-identity
      ambassador_id: private
      prefix: /api/mob/emp/identity
      rewrite: ""
      service: rm-auth-empmobile-identity
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: rm-auth-empmobile-identity-test
      prefix: /api/mob/user/identity/
      rewrite: ""
      service: rm-auth-empmobile-identity-test
      ---             // The extra triple dash/document separator```
```
Removing that fixes the issue.
