### ISSUE TITLE
Getting started guide fails with new minikube based installation

### ISSUE THREAD

**Issue by exu** [datawire/ambassador#720]
**Describe the bug**
Ambassador doesn't start with clean minikube installation 

**To Reproduce**
Follow https://www.getambassador.io/user-guide/getting-started tutorial with rbac based configuration

```
kubectl apply -napi -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml
```

after that I've receive error in ambassador pod logs 

```
❯ kubectl logs ambassador-d85dc8c4-cqlq6 ambassador -napi
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 451, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 431, in main
    sync(restarter)
  File "/ambassador/kubewatch.py", line 259, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11650, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11753, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 09 Aug 2018 12:45:35 GMT', 'Content-Length': '264'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:api:ambassador\" cannot list configmaps in the namespace \"api\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /ambassador/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down (1)
```

**Expected behavior**
Working ambassador deployment

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.38.0]
 - Kubernetes environment : minikube version: v0.28.0

**Additional context**
Clean installation with previously deleted minikube image 
host os archlinux.

**Comment by richarddli** [comment]
I believe this is resolved
