### ISSUE TITLE
shadow option doesn't work with K8S Loadbalancer service type 

### ISSUE THREAD

**Issue by duckty** [datawire/ambassador#896]
**Describe the bug**
When enabing "shadow: true" option to mirror requests for k8s loadbalancer  service type. Ambassador threw an invalid configuration

**To Reproduce**
1. create an dummy service 
```cat httpbin.yaml 
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  annotations:
    getambassador.io/config: |    
       ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: kong_dev_test
      prefix: /mydomain/
      rewrite: ""
      service: https://loadbalancer1-1090333193.us-west-2.elb.amazonaws.com:443
      host_rewrite: kong-kube-dev.mydomain.com
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: kong_dev_test_shadowing
      prefix: /mydomain/
      rewrite: ""
      service: https://loadbalancer2-1995339605.us-west-2.elb.amazonaws.com:443
      host_rewrite: kong-kube-staging.mydomain.com
      shadow: true
      timeout_ms: 500
spec:
  ports:
  - name: httpbin
    port: 80
```
2. kubectl apply -f httpbin.yaml
3. See the error from one of ambassador pod
```2018-10-18 01:37:24 kubewatch 0.40.0 INFO: generating config with gencount 3 (1 change)
2018-10-18 01:37:24 kubewatch 0.40.0 ERROR: httpbin-default.yaml.2 (httpbin-default.yaml): <RichStatus BAD error=not a valid Mapping: Additional properties are not allowed ('getambassador.io/config' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'$schema': 'http://json-schema.org/schema#',
     'additionalProperties': False,
     'definitions': {'mapStrStr': {'additionalProperties': {'type': ['string',
                                                                     'boolean']},
                                   'type': 'object'},
                     'rateLimit': {'additionalProperties': False,
                                   'properties': {'descriptor': {'type': 'string'},
                                                  'headers': {'items': {'type': 'string'},
                                                              'type': 'array'}},
                                   'type': 'object'}},
     'id': 'https://getambassador.io/schemas/mapping.json',
     'properties': {'add_request_headers': {'$ref': '#/definitions/mapStrStr'},
                    'ambassador_id': {'anyOf': [{'type': 'string'},
                                                {'items': {'type': 'string'},
                                                 'type': 'array'}]},
                    'apiVersion': {'enum': ['ambassador/v0']},
                    'auto_host_rewrite': {'type': 'boolean'},
                    'case_sensitive': {'type': 'boolean'},
                    'circuit_breaker': {'type': 'string'},
                    'cors': {'additionalProperties': False,
                             'properties': {'credentials': {'type': 'boolean'},
                                            'exposed_headers': {'anyOf': [{'type': 'string'},
                                                                          {'items': {'type': 'string'},
                                                                           'type': 'array'}]},
                                            'headers': {'anyOf': [{'type': 'string'},
                                                                  {'items': {'type': 'string'},
                                                                   'type': 'array'}]},
                                            'max_age': {'type': 'string'},
                                            'methods': {'anyOf': [{'type': 'string'},
                                                                  {'items': {'type': 'string'},
                                                                   'type': 'array'}]},
                                            'origins': {'anyOf': [{'type': 'string'},
                                                                  {'items': {'type': 'string'},
                                                                   'type': 'array'}]}},
                             'type': 'object'},
                    'envoy_override': {'type': 'object'},
                    'grpc': {'type': 'boolean'},
                    'headers': {'$ref': '#/definitions/mapStrStr'},
                    'host': {'type': 'string'},
                    'host_redirect': {'type': 'boolean'},
                    'host_regex': {'type': 'boolean'},
                    'host_rewrite': {'type': 'string'},
                    'kind': {'type': 'string'},
                    'method': {'type': 'string'},
                    'method_regex': {'type': 'boolean'},
                    'modules': {'items': {'type': 'object'},
                                'type': 'array'},
                    'name': {'type': 'string'},
                    'outlier_detection': {'type': 'string'},
                    'path_redirect': {'type': 'string'},
                    'precedence': {'type': 'integer'},
                    'prefix': {'type': 'string'},
                    'prefix_regex': {'type': 'boolean'},
                    'priority': {'type': 'string'},
                    'rate_limits': {'items': {'$ref': '#/definitions/rateLimit'},
                                    'type': 'array'},
                    'regex_headers': {'$ref': '#/definitions/mapStrStr'},
                    'rewrite': {'type': 'string'},
                    'service': {'type': 'string'},
                    'shadow': {'type': 'boolean'},
                    'timeout_ms': {'type': 'integer'},
                    'tls': {'type': ['string', 'boolean']},
                    'use_websocket': {'type': 'boolean'},
                    'weight': {'type': 'integer'}},
     'required': ['apiVersion', 'kind', 'name', 'service', 'prefix'],
     'type': 'object'}

On instance:
    {'apiVersion': 'ambassador/v0',
     'getambassador.io/config': '',
     'kind': 'Mapping',
     'name': 'kong-new-staging-shadow',
     'prefix': '/mydomain/',
     'rewrite': '',
     'service': 'quality-control-be-staging.default',
     'shadow': True} hostname=ambassador-5c749668c8-252jx resolvedname=100.98.237.38 version=0.40.0>
2018-10-18 01:37:24 kubewatch 0.40.0 ERROR: ERROR ERROR ERROR Starting with configuration errors
2018-10-18 01:37:24 kubewatch 0.40.0 INFO: cluster_https___loadbalancer1_1090333193_us_west_2_elb_amazonaws_com_443_otls_hr_kong_kube_dev_mydomain_com => cluster_https___aee27c5e1e6f611e7a541026-0
2018-10-18 01:37:24 kubewatch 0.40.0 INFO: cluster_shadow_https___loadbalancer2_1995339605_us_west_2_elb_amazonaws_com_443_otls_hr_kong_kube_staging_mydomain_com => cluster_shadow_https___a9470a6c3ea0811e7-0
2018-10-18 01:37:25 kubewatch 0.40.0 INFO: Scout reports {"latest_version": "0.40.0", "application": "ambassador", "notices": [], "cached": false, "timestamp": 1539826644.869249}
[2018-10-18 01:37:25.333][247][info][config] source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2018-10-18 01:37:25.336][247][info][upstream] source/common/upstream/cluster_manager_impl.cc:132] cm init: all clusters initialized
[2018-10-18 01:37:25.336][247][info][config] source/server/configuration_impl.cc:60] loading 2 listener(s)
[2018-10-18 01:37:25.350][247][critical][main] source/server/config_validation/server.cc:48] error initializing configuration '/ambassador/ambassador-config-3-envoy.json': route: unknown shadow cluster 'cluster_shadow_https___loadbalancer2_1995339605_us_west_2_elb_amazonaws_com_443_otls_hr_kong_kube_staging_mydomain_com'
2018-10-18 01:37:25 kubewatch 0.40.0 INFO: Invalid envoy config
2018-10-18 01:37:25 kubewatch 0.40.0 INFO: {
  "listeners": [
    
    {
      "address": "tcp://0.0.0.0:443",
      
      "ssl_context": {"cert_chain_file": "/ambassador/certs/tls.crt",
          "private_key_file": "/ambassador/certs/tls.key"
      },"filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {"codec_type": "auto",
            "stat_prefix": "ingress_http",
            "access_log": [
              {
                "format": "ACCESS [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n",
                "path": "/dev/fd/1"
              }
            ],
            
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],"require_ssl": "all","routes": [
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_ready","prefix_rewrite": "/ambassador/v0/check_ready","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_alive","prefix_rewrite": "/ambassador/v0/check_alive","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/","prefix_rewrite": "/ambassador/v0/","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/mydomain/","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_kong_new_staging_openresty_default", "weight": 50.0 },
                                  
                                    { "name": "cluster_https___aee27c5e1e6f611e7a541026-0", "weight": 50.0 }
                                  
                              ]
                          },
                          "shadow": {
                            "cluster": "cluster_shadow_https___loadbalancer2_1995339605_us_west_2_elb_amazonaws_com_443_otls_hr_kong_kube_staging_mydomain_com"
                          }

                      
                    }
                    
                    
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "cors",
                "config": {}
              },{"type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    },
    {
      "address": "tcp://0.0.0.0:80",
      
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {"codec_type": "auto",
            "stat_prefix": "ingress_http",
            "access_log": [
              {
                "format": "ACCESS [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n",
                "path": "/dev/fd/1"
              }
            ],
            
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],"require_ssl": "all","routes": [
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_ready","prefix_rewrite": "/ambassador/v0/check_ready","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_alive","prefix_rewrite": "/ambassador/v0/check_alive","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/","prefix_rewrite": "/ambassador/v0/","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/mydomain/","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_kong_new_staging_openresty_default", "weight": 50.0 },
                                  
                                    { "name": "cluster_https___aee27c5e1e6f611e7a541026-0", "weight": 50.0 }
                                  
                              ]
                          },
                          "shadow": {
                            "cluster": "cluster_shadow_https___loadbalancer2_1995339605_us_west_2_elb_amazonaws_com_443_otls_hr_kong_kube_staging_mydomain_com"
                          }

                      
                    }
                    
                    
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "cors",
                "config": {}
              },{"type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "address": "tcp://127.0.0.1:8001",
    "access_log_path": "/tmp/admin_access_log"
  },
  
  "cluster_manager": {
    "clusters": [
      {
        "name": "cluster_127_0_0_1_8877",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://127.0.0.1:8877"
          }
          
        ]},
      {
        "name": "cluster_https___aee27c5e1e6f611e7a541026-0",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://loadbalancer1-1090333193.us-west-2.elb.amazonaws.com:443"
          }
          
        ],
        "ssl_context": {
          
          "sni": "kong-kube-dev.mydomain.com"
          
        }},
      {
        "name": "cluster_kong_new_staging_openresty_default",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://kong-new-staging-openresty.default:80"
          }
          
        ]},
      {
        "name": "cluster_shadow_https___a9470a6c3ea0811e7-0",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://loadbalancer2-1995339605.us-west-2.elb.amazonaws.com:443"
          }
          
        ],
        "ssl_context": {
          
          "sni": "kong-kube-staging.mydomain.com"
          
        }}
      
    ]
  },
  
  "statsd_udp_ip_address": "127.0.0.1:8125",
  "stats_flush_interval_ms": 1000
}
2018-10-18 01:37:25 kubewatch 0.40.0 ERROR: could not restart Envoy
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 126, in run
    self.restart()
  File "/ambassador/kubewatch.py", line 135, in restart
    config = self.generate_config(output)
  File "/ambassador/kubewatch.py", line 192, in generate_config
    raise ValueError("Unable to generate config")
ValueError: Unable to generate config
```

**Expected behavior**
The configuration should work 

**Versions (please complete the following information):**
 - Ambassador: 0.39.0 and 0.40.0
 - Kubernetes environment in AWS with kops
 - Version 1.10.6

**Additional context**
the shadow option working fine with the following 

```
getambassador.io/config: |
      ---       
      apiVersion: ambassador/v0
      kind: Mapping
      name: kong-new-staging-openresty-mapping
      prefix: /mydomain2/
      rewrite: ""
      service: kong-new-staging-openresty.default
      ---       
      apiVersion: ambassador/v0
      kind: Mapping
      name: kong-new-staging-shadow
      prefix: /mydomain2/
      rewrite: ""
      service: quality-control-be-staging.default
      shadow: true 
```

**Comment by moskyb** [comment]
We're running into the problem with `ExternalName` type services as well - is this a known issue within ambassador? If so, could we get a docs update saying "Traffic Shadowing only works with ClusterIP services" or something similar?

**Comment by slamdev** [comment]
any updates on the issue?
